# Generated by Django 5.2.8 on 2025-11-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('category', 'capacity', 'has_child_bed')},
        ),
    ]
